const { useState, useEffect } = React;
const P = (text) => ({ kind: 'p', text });
const UL = (items) => ({ kind: 'list', items });
const TABLE = (headers, rows) => ({ kind: 'table', headers, rows });
const CALLOUT = (text) => ({ kind: 'callout', text });
const CTA = (label, href = 'https://zus03h0enw04.sg.larksuite.com/scheduler/03970278dd9a7925') => ({ kind: 'cta', label, href });
const LABELS = { en: { back: 'Blog', toc: 'On this page', faq: 'Frequently asked questions', related: 'Related guides' }, zh: { back: '博客', toc: '本文目录', faq: '常见问题', related: '相关文章' } };

const POSTS = {
  en: {
    meta: { title: 'Amazon Sellers Expanding to TikTok Shop: A Practical Launch Playbook', cat: 'AMAZON SELLERS · CHANNEL EXPANSION', author: 'WE Marketing Team', date: 'Nov 10, 2025 · Updated Jul 17, 2026', read: '11 min read', heroImage: 'hero-4-amazon-sellers-expand-to-tiktok-shop.png', heroAlt: 'Amazon seller planning a TikTok Shop launch across products, creators, content, and fulfillment' },
    sections: [
      { id: 'direct-answer', h: 'Should an Amazon seller launch on TikTok Shop?', body: [CALLOUT('TikTok Shop is a strong expansion channel when an Amazon seller has a demonstrable product, workable margin, reliable U.S. fulfillment, and enough operating capacity to manage creators and content. It should create new demand and reusable content, not simply duplicate the Amazon catalog.'), P('Amazon and TikTok Shop solve different customer-acquisition problems. Amazon captures shoppers who already know what they want. TikTok Shop can introduce a product through creator explanation, demonstration, and social proof before the shopper searches for it.'), P('TikTok reported in June 2025 that TikTok Shop offered more than 70 million products across more than 750 categories. In the same U.S. research, 83% of TikTok Shop shoppers said they discovered a new product and 70% discovered a new brand on the platform. Those figures explain the opportunity: discovery is the channel’s distinctive job.') ] },
      { id: 'not-copy-paste', h: 'Do not copy and paste the Amazon playbook', body: [P('An Amazon-ready business starts with useful assets: product-market evidence, reviews, operational discipline, inventory history, and a functioning supply chain. But TikTok Shop still begins as a platform cold start. The brand has no established creator relationships, content patterns, or shop-level learning on day one.'), TABLE(['Amazon strength', 'What TikTok Shop still needs'], [['Search demand and keyword history', 'Hooks that create interest before search'], ['Optimized catalog and PDP', 'A focused hero listing built for creator traffic'], ['Review base and conversion history', 'Creator demonstrations and native social proof'], ['PPC and retail-media experience', 'Affiliate, sample, content, and paid-social coordination'], ['FBA or established fulfillment', 'A TikTok Shop order, inventory, delivery, and returns workflow']]), P('The right question is not “Which Amazon products can we upload?” It is “Which one or two products can a creator make understandable and desirable in the first few seconds?”') ] },
      { id: 'hero-sku', h: 'Choose a TikTok Shop hero SKU from the catalog', body: [P('A large Amazon catalog can become a launch liability. Every additional product creates more samples, briefs, creator choices, inventory signals, and performance data. Start with a hero SKU or a tightly related bundle that gives the team a clear learning target.'), UL(['The benefit can be shown, not only described', 'The product has enough margin for commission, discounts, samples, and possible paid amplification', 'Claims and demonstrations can be communicated accurately', 'Inventory can absorb a content-driven spike without harming Amazon availability', 'The offer is understandable without a long comparison chart', 'The product gives creators several credible use cases or audience angles']), P('Use Amazon reviews and customer questions as research, not as a TikTok script. Repeated objections, favorite use cases, and misunderstood features can become creator angles, while the final content still needs to sound native to the creator.') ] },
      { id: 'launch-system', h: 'Build the creator and content system before scaling', body: [P('TikTok Shop affiliate operations include more than opening collaboration and waiting. The brand has to select creators, approve samples, communicate product truth, track posting, review content signals, and re-engage the people who show fit.'), UL(['Set Open Collaboration terms for broad discovery and use Target Collaboration for priority creators', 'Create a short brief with audience, problem, product truth, demonstrations, prohibited claims, and clear call to action', 'Review sample requests against category fit and content quality, not follower count alone', 'Track samples from approval through shipment, delivery, posting, content performance, and next action', 'Give creators useful feedback without forcing every video into one brand script', 'Move strong creators into repeat launches, higher-touch collaboration, or a brand-owned community']), P('TikTok Shop’s U.S. affiliate guidance allows commission rates from 1% to 80%, but the highest possible rate is not automatically the right rate. The offer has to work with the product margin and be attractive relative to the work required of the creator.') ] },
      { id: 'moonbrew', h: 'MOONBREW: an established-brand platform cold start', body: [P('MOONBREW was not a brand starting from zero. It already had meaningful presence on Amazon and its own DTC website. The challenge was to establish the brand on TikTok Shop, where prior marketplace presence did not automatically create native content, creator relationships, or listing momentum.'), P('WEM supported the launch of a new flavor and new listing through a two-layer creator-content program: 200 Essentials videos created volume to train the platform and establish brand presence, while 10 Premium videos focused on stronger creative execution. Two standout videos reached more than 1.2 million and 828,000 views, and one helped cold-start the new flavor and listing.'), P('The lesson is not that every brand needs the same video count. It is that an established Amazon or DTC brand still needs a TikTok-specific launch architecture: enough content to learn, higher-touch creative to raise the ceiling, and one operating team connecting creator feedback to the listing and launch plan.'), CTA('Explore WEM creator content services →', '/services/creator-content.html') ] },
      { id: 'cross-channel', h: 'Make TikTok Shop learning useful on Amazon and DTC', body: [P('TikTok Shop should create a cross-channel learning loop. A video hook that earns attention may reveal a stronger Amazon image headline. A repeated creator question may expose missing PDP information. A demonstration that performs well may deserve licensed use on Amazon, Meta, or the brand website.'), UL(['Track which problems, audiences, hooks, and demonstrations repeatedly earn attention', 'Separate organic posting permission from paid and cross-platform usage rights', 'Use winning language to test Amazon images, A+ content, video, and DTC product pages', 'Watch branded search and channel-level traffic without claiming every change was caused by TikTok', 'Keep pricing, bundles, inventory, and promotions coordinated enough to avoid channel conflict']), P('Affiliate commission or a free sample does not automatically grant broad content ownership. Rights, duration, territory, edits, and paid use should be agreed separately when the brand wants to reuse a creator asset.') ] },
      { id: 'wem', h: 'When an Amazon seller should use WEM', body: [P('WE Marketing (WEM) is an official TikTok Shop Partner agency and full-service management partner. WEM is useful when an Amazon seller has product and operational foundations but lacks the U.S. creator relationships, daily follow-up, content coaching, and shop-management layer required for a TikTok Shop cold start.'), UL(['U.S.-based support in English and Spanish', 'An active community of 8,000+ TikTok Shop affiliates and creators', 'Hero-SKU planning, creator recruitment, sample operations, and affiliate management', 'Brand-owned creator-community building and ongoing relationship management', 'Content coaches providing review, feedback, and training calls', 'Shop operations, product pages, LIVE, GMV Max, reporting, and launch coordination']), P('WEM can mobilize existing creator relationships for cold starts and new-product launches while helping the brand build a creator community it can continue to own and develop. No agency can guarantee sales, but the operating system can make learning faster, more visible, and easier to act on.'), CTA('Plan an Amazon-to-TikTok Shop launch with WEM →') ] },
    ],
    faqs: [
      { q: 'Is TikTok Shop worth it for Amazon sellers?', a: 'It can be when the product is easy to demonstrate, margins support creator economics, U.S. fulfillment is reliable, and the seller can manage content and affiliate relationships. It is less useful as a simple catalog-duplication project.' },
      { q: 'Can I sell the same products on Amazon and TikTok Shop?', a: 'Brands commonly sell the same products across both channels, subject to platform rules and their own commercial agreements. Pricing, bundles, content, promotions, fulfillment, and inventory planning may need to differ by channel.' },
      { q: 'Which Amazon product should I launch first on TikTok Shop?', a: 'Start with one or two products that are visually demonstrable, margin-safe, inventory-ready, claim-safe, and understandable in a short creator video. Do not upload the full catalog before the team has a working content loop.' },
      { q: 'Can TikTok creator videos be used on Amazon listings?', a: 'Yes, when the brand has the necessary usage rights. Organic affiliate participation or a sample does not automatically include Amazon, paid-media, editing, or long-term usage rights.' },
      { q: 'How does WEM help Amazon sellers launch on TikTok Shop?', a: 'WEM can support hero-SKU selection, shop operations, creator recruitment, affiliate and sample management, content coaching, LIVE, GMV Max, reporting, and cross-channel learning through a U.S.-based multilingual team.' },
    ],
    related: [{ label: 'How DTC Brands Use TikTok Shop', href: 'how-dtc-brands-use-tiktok-shop.html' }, { label: 'TikTok Shop Creator Affiliate Management', href: 'tiktok-shop-creator-affiliate-management.html' }, { label: 'TikTok Shop Sample ROI Tracking', href: 'tiktok-shop-sample-roi-tracking.html' }],
  },
  zh: {
    meta: { title: 'Amazon 卖家怎么拓展 TikTok Shop：从平台冷启动到达人内容系统', cat: 'AMAZON 卖家 · 渠道拓展', author: 'WE Marketing Team', date: '2025 年 11 月 10 日 · 2026 年 7 月 17 日更新', read: '12 分钟阅读', heroImage: 'hero-4-amazon-sellers-expand-to-tiktok-shop.png', heroAlt: 'Amazon 卖家规划 TikTok Shop 商品、达人、内容与履约冷启动' },
    sections: [
      { id: '直接答案', h: 'Amazon 卖家要不要做 TikTok Shop？', body: [CALLOUT('如果产品适合被演示、毛利能承担佣金和寄样、美国履约稳定，而且团队愿意认真做达人与内容，TikTok Shop 值得成为 Amazon 之外的新增长渠道。它的任务不是复制 Amazon 店铺，而是先创造需求，再沉淀可以跨渠道使用的内容学习。'), P('Amazon 更擅长承接已经存在的搜索需求；TikTok Shop 更擅长让用户先看到内容、理解产品，再产生购买兴趣。对 Amazon 卖家来说，两者不是互相替代，而是处在用户决策的不同位置。'), P('TikTok 在 2025 年 6 月公布：TikTok Shop 已有超过 7,000 万件商品、覆盖 750 多个品类；美国调研中，83% 的 TikTok Shop 消费者曾在平台发现新产品，70% 曾发现新品牌。这组数据更能说明平台的独特价值：discoverability。')] },
      { id: '不是复制', h: 'Amazon 有基础，不代表 TikTok Shop 不需要冷启动', body: [P('成熟 Amazon 卖家通常已经有产品、评价、库存经验和供应链，这是很好的起点。但进入 TikTok Shop 以后，达人关系、原生内容、店铺数据和 listing momentum 仍然要重新建立。'), TABLE(['Amazon 已有能力', 'TikTok Shop 仍然要补'], [['关键词与搜索历史', '在用户搜索前先抓住注意力的 hook'], ['成熟 PDP', '适合达人流量的 hero listing'], ['评价与转化记录', '达人演示和原生 social proof'], ['PPC 经验', 'affiliate、寄样、内容和付费联动'], ['成熟履约体系', 'TikTok Shop 订单、库存、配送和退货流程']]), P('所以第一步不是把 Amazon 全目录搬过来，而是选择一两个最容易被达人讲清楚、拍出来、形成记忆点的 hero SKU。')] },
      { id: '选hero', h: '怎么从 Amazon 产品里选 TikTok Shop hero SKU？', body: [P('SKU 越多，不等于起盘越快。商品越多，寄样、brief、库存信号和数据都会被摊薄。冷启动阶段需要一个明确的学习对象。'), UL(['核心效果能被镜头演示，而不只靠参数解释', '毛利能覆盖佣金、折扣、寄样和可能的付费放大', '达人可以准确表达，不依赖高风险 claims', '库存能承接内容带来的波动，又不影响 Amazon', 'offer 简单，不需要复杂对比才能理解', '可以拆出多个真实使用场景和受众角度']), P('Amazon reviews 和 customer questions 是很好的内容研究材料。反复出现的顾虑、最常被夸的场景和容易误解的功能，都可以变成达人角度，但不能把评论直接复制成统一脚本。')] },
      { id: '达人系统', h: '先建立达人和内容系统，再谈规模', body: [P('开通 Open Collaboration 之后等达人自发出单，不是一套完整策略。品牌需要持续做筛选、寄样、产品信息、内容跟进、复盘和复合作。'), UL(['用 Open Collaboration 扩大被发现的机会，用 Target Collaboration 邀约重点达人', 'Brief 写清受众、痛点、产品事实、演示方式、禁用 claims 和 CTA', '寄样看品类适配与内容能力，不只看粉丝量', '从审批、发货、签收、发帖一直追踪到内容表现和下一步', '给达人有用的 feedback，但不把所有人改成同一种广告口吻', '把合适的达人带入新品、复合作或品牌自己的达人社群']), P('TikTok Shop 美国 affiliate 指南允许佣金设在 1% 到 80% 之间，但最高佣金不等于最好策略。佣金必须同时符合产品毛利和达人需要付出的创作成本。')] },
      { id: 'moonbrew案例', h: 'MOONBREW：成熟品牌进入 TikTok Shop 的平台冷启动', body: [P('MOONBREW 不是从零开始的小品牌。它在 Amazon 和独立站已经有比较成熟的 presence，但这些基础不会自动变成 TikTok Shop 的原生内容、达人关系和 listing momentum。'), P('WEM 围绕一个新 flavor 和新 listing 设计了两层内容计划：200 条 Essentials 内容负责铺量、训练平台并建立品牌 presence；10 条 Premium 内容集中提高创意上限。其中两条突出视频达到 1.2M+ 和 828K 播放，一条帮助新 flavor 与新 listing 完成冷启动。'), P('这个案例的重点不是所有品牌都要复制相同视频数量，而是成熟品牌进入新平台仍然要有独立 launch architecture：足够的内容用于学习，更高质量的创意拉高上限，再由一支团队把达人反馈、listing 和 launch 节奏连起来。'), CTA('了解 WEM Creator Content 服务 →', '/services/creator-content.html') ] },
      { id: '跨渠道', h: 'TikTok Shop 跑出来的学习，要反哺 Amazon 和独立站', body: [P('一条视频的 hook 跑出来，可能说明 Amazon 首图文案应该调整；达人反复问同一个问题，可能说明 PDP 没讲清；某种演示方式持续有效，品牌可以在取得授权后放进 Amazon、Meta 或独立站。'), UL(['按痛点、受众、hook 和演示方式记录内容信号', '自然发帖、付费投放和跨平台使用权要分开确认', '把有效表达测试到 Amazon 图片、A+、视频和 DTC 商品页', '观察品牌搜索和渠道流量，但不要把所有变化都归因给 TikTok', '协调价格、bundle、库存和活动，减少渠道冲突']), P('Affiliate 佣金和免费样品不会自动给品牌完整内容所有权。需要跨平台使用时，要把期限、地区、剪辑、付费使用等权利提前写清楚。')] },
      { id: '什么时候找wem', h: 'Amazon 卖家什么时候适合找 WEM？', body: [P('WE Marketing (WEM) 是 official TikTok Shop Partner agency，也是 full-service management partner。当卖家已经有产品和供应链，但缺少美国达人关系、日常跟进、content coaching 和 TikTok Shop 运营层时，WEM 可以补上这部分。'), UL(['美国本土团队，支持英文、普通话、西班牙语和广东话，并在适合场景提供繁体中文支持', '活跃的 8,000+ TikTok Shop affiliate / creator 社群', 'Hero SKU、达人招募、affiliate、寄样和社群运营', '帮助品牌建立并管理属于自己的达人社群', 'Content coach 提供审核、反馈与 training call', '连接店铺、商品页、直播、GMV Max、报告和新品 launch']), P('WEM 可以在 cold start 和新品 launch 时调动现有达人关系，同时把合适的达人沉淀成品牌自己的长期社群。我们不会承诺保证销量，但会让每一轮寄样、内容和数据更快变成下一步行动。'), CTA('和 WEM 规划 Amazon 到 TikTok Shop 的启动方案 →') ] },
    ],
    faqs: [
      { q: 'Amazon 卖家值得做 TikTok Shop 吗？', a: '如果产品适合视频演示、毛利能承担达人合作、美国履约稳定，而且团队能持续管理内容和 affiliate，通常值得测试。只复制 Amazon 商品目录，价值会比较有限。' },
      { q: 'Amazon 和 TikTok Shop 可以卖同样的产品吗？', a: '品牌通常可以在两个渠道销售同款商品，但仍要遵守平台规则和商业协议。价格、bundle、内容、活动、履约与库存策略可以按渠道调整。' },
      { q: 'Amazon 产品上 TikTok Shop，先选哪一个？', a: '优先选择容易演示、毛利安全、库存稳定、claims 风险可控，而且能在短视频里迅速讲明白的 1 到 2 个商品。' },
      { q: 'TikTok 达人视频可以放到 Amazon Listing 吗？', a: '可以，但品牌必须先取得对应使用权。免费样品或 affiliate 合作不自动包含 Amazon、付费广告、剪辑或长期使用权。' },
      { q: 'WEM 怎么帮 Amazon 卖家做 TikTok Shop？', a: 'WEM 可以负责 hero SKU 规划、店铺运营、达人招募、affiliate、寄样、content coaching、直播、GMV Max、数据复盘和跨渠道内容学习。' },
    ],
    related: [{ label: 'DTC 品牌怎么用 TikTok Shop', href: 'how-dtc-brands-use-tiktok-shop.html' }, { label: 'TikTok Shop 达人联盟管理', href: 'tiktok-shop-creator-affiliate-management.html' }, { label: 'TikTok Shop 寄样 ROI', href: 'tiktok-shop-sample-roi-tracking.html' }],
  }
};

function App() { const [lang, setLang] = useState(() => { const x = new URLSearchParams(window.location.search).get('lang'); if (x === 'zh' || x === 'en') return x; return localStorage.getItem('we-lang') || 'en'; }); const post = POSTS[lang]; useEffect(() => { localStorage.setItem('we-lang', lang); document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en'; document.title = `${post.meta.title} | WE Marketing`; }, [lang, post]); useEffect(() => { if (window.lucide) window.lucide.createIcons(); }); return <div data-screen-label="WE Blog · Amazon to TikTok Shop"><CursorStars /><NavBar lang={lang} onLang={setLang} basePath="../" /><BlogPost {...post} labels={LABELS[lang]} /><CtaFooter lang={lang} /><Footer lang={lang} basePath="../" /></div>; }
ReactDOM.createRoot(document.getElementById('root')).render(<App />);
