const { useState, useEffect } = React;
const P = (text) => ({ kind: 'p', text });
const UL = (items) => ({ kind: 'list', items });
const TABLE = (headers, rows) => ({ kind: 'table', headers, rows });
const CALLOUT = (text) => ({ kind: 'callout', text });
const CTA = (label, href = 'https://zus03h0enw04.sg.larksuite.com/scheduler/03970278dd9a7925') => ({ kind: 'cta', label, href });
const LABELS = { en: { back: 'Blog', toc: 'On this page', faq: 'Frequently asked questions', related: 'Related guides' }, zh: { back: '博客', toc: '本文目录', faq: '常见问题', related: '相关文章' } };

const POSTS = {
  en: {
    meta: { title: 'How DTC Brands Use TikTok Shop: From Creator Discovery to Cross-Channel Growth', cat: 'DTC · CREATOR COMMERCE', author: 'WE Marketing Team', date: 'Mar 18, 2026 · Updated Jul 17, 2026', read: '11 min read', heroImage: 'hero-8-how-dtc-brands-use-tiktok-shop.png', heroAlt: 'DTC brand team connecting TikTok Shop creators, content, product pages, and cross-channel growth' },
    sections: [
      { id: 'direct-answer', h: 'What role should TikTok Shop play for a DTC brand?', body: [CALLOUT('TikTok Shop should be a creator-led discovery, conversion, and learning channel, not a replacement for the brand’s website. The strongest DTC programs use creator content to sell in-platform, reveal stronger customer language, and improve Amazon, Meta, and the DTC product experience.'), P('DTC teams already understand product storytelling, merchandising, retention, and customer feedback. TikTok Shop adds a different operating motion: many creators test many ways to explain the same product, while shoppers can move from discovery to checkout without leaving the platform.'), P('TikTok reported in June 2025 that 83% of surveyed U.S. TikTok Shop shoppers discovered a new product and 70% discovered a new brand on the platform. That makes TikTok Shop especially relevant when the DTC growth problem is not checkout infrastructure but finding new audiences and fresh creative angles.') ] },
      { id: 'channel-role', h: 'Protect the DTC site by giving each channel a clear job', body: [P('A DTC brand does not need to choose between TikTok Shop and its own site. It needs to decide what each surface is responsible for and how learning moves between them.'), TABLE(['Channel', 'Primary job'], [['TikTok Shop', 'Creator-led discovery, native demonstration, affiliate conversion, and fast content learning'], ['DTC website', 'Full brand story, bundles, subscriptions, CRM capture, merchandising, and repeat-purchase experience'], ['Amazon', 'High-intent search capture, comparison, retail trust, and convenience'], ['Meta', 'Paid creative testing, retargeting, prospecting, and controlled audience scale']]), P('Channel conflict usually begins when price, bundles, inventory, or customer promises are managed independently. A cross-channel calendar and clear offer architecture help the brand create differentiation without making loyal customers feel penalized.') ] },
      { id: 'readiness', h: 'DTC readiness starts with economics and operations', body: [P('A visually appealing brand can still be unready for TikTok Shop. The team should understand contribution margin after product cost, fulfillment, platform fees, discounts, affiliate commission, samples, creator fees, and paid amplification.'), UL(['Choose one or two creator-friendly hero products', 'Confirm U.S. inventory, shipping, returns, and customer-service capacity', 'Write claim-safe product truth that creators can understand quickly', 'Decide how much margin is available for commission and launch offers', 'Prepare samples and a workflow for approval, delivery, posting, and follow-up', 'Assign one owner who can connect creators, shop, content, inventory, and weekly decisions']), P('The point is not to predict every result. It is to avoid scaling traffic into an offer or operation that has not been tested.') ] },
      { id: 'content-system', h: 'Build a creator-content portfolio, not one perfect ad', body: [P('DTC creative teams often arrive with polished brand assets. Those assets can establish visual identity, but TikTok Shop also needs creator-native proof: demonstrations, routines, objections, comparisons, reactions, and specific use cases.'), UL(['Essentials content creates volume and tests many credible angles', 'Premium content gives priority concepts more planning, production, and coaching', 'Affiliate content connects creator storytelling directly to commerce', 'Licensed winners can move into Meta, Amazon, and DTC placements when rights allow', 'Content coaching improves product accuracy and creative execution without removing the creator’s voice']), P('The portfolio approach matters because a brand cannot reliably choose the winning hook in a conference room. It needs enough real market tests to see which combinations of audience, problem, proof, and offer earn attention.') ] },
      { id: 'moonbrew', h: 'MOONBREW: launching a new flavor on a new platform', body: [P('MOONBREW already had meaningful presence on Amazon and its DTC website. TikTok Shop was therefore not a brand-from-zero project; it was a platform cold start. The brand still needed native content, creator relationships, a new listing, and a launch rhythm built for TikTok.'), P('WEM supported a new flavor and new listing through two content layers. The program included 200 Essentials videos to build volume and brand presence, plus 10 Premium videos designed to raise the creative ceiling. Two standout videos reached more than 1.2 million and 828,000 views, and one helped cold-start the new flavor and listing.'), P('This is the practical DTC lesson: existing brand equity improves the starting position, but it does not replace platform-specific execution. Content volume creates learning; higher-touch creative creates breakout potential; coordinated shop and creator operations turn those signals into a launch system.'), CTA('See how WEM builds creator content programs →', '/services/creator-content.html') ] },
      { id: 'community', h: 'Turn creator outreach into a brand-owned community', body: [P('A DTC brand gains more durable value when it stops treating every creator as a one-time transaction. The goal is to identify fit, support better content, re-engage reliable creators, and build a community around future products and launches.'), UL(['Recruit by category fit, audience context, content quality, and working behavior, not follower count alone', 'Track sample and communication history so creators do not receive repetitive outreach', 'Give top creators early access to launches and clearer product education', 'Use content review and training calls when the relationship calls for higher-touch support', 'Record creator questions and objections as product-page and FAQ inputs', 'Separate affiliate commission, flat fees, and content usage rights in every agreement']), P('WEM’s active community of 8,000+ TikTok Shop affiliates and creators can help a brand move faster at cold start. WEM also helps brands recruit and manage a community of their own, so creator knowledge and relationships become a long-term brand asset.') ] },
      { id: 'weekly-loop', h: 'Run one weekly commerce review across content and channels', body: [P('A useful weekly review should answer what the team will change, not merely recite views and GMV. DTC operators should look at content, product pages, offers, creators, inventory, customer questions, and cross-channel signals together.'), TABLE(['Signal', 'Possible action'], [['A hook repeatedly holds attention', 'Test the language in the TikTok listing, DTC page, Amazon PDP, or Meta creative'], ['Creators repeat the same objection', 'Clarify the product page, brief, FAQ, packaging insert, or claim guidance'], ['One SKU converts while the catalog stays flat', 'Concentrate samples, content, inventory, and paid amplification around the hero'], ['Views rise but conversion does not', 'Audit audience fit, price, offer, listing clarity, reviews, and delivery expectations'], ['A creator performs reliably', 'Plan repeat content, launch access, community role, or a separately negotiated paid scope']]), P('Cross-channel lift should be measured carefully. Branded search, DTC sessions, Amazon demand, and Meta creative performance can move alongside TikTok activity, but correlation should not be presented as guaranteed attribution.') ] },
      { id: 'wem', h: 'How WEM supports DTC brands on TikTok Shop', body: [P('WE Marketing (WEM) is an official TikTok Shop Partner agency and full-service management partner. WEM connects creator affiliates, creator content, samples, community management, product pages, LIVE, GMV Max, customer experience, and reporting instead of operating them as disconnected vendors.'), UL(['A U.S.-based team supporting English and Spanish', 'An active community of 8,000+ TikTok Shop affiliates and creators', 'Cold-start and new-product-launch activation through established creator relationships', 'Creator recruitment and ongoing management for brand-owned communities', 'Content coaches providing reviews, feedback, and training calls', 'Shop operations, LIVE, paid amplification, and weekly cross-channel learning']), P('WEM is most useful when a DTC brand has real product and customer foundations but needs an operating partner to build TikTok-native creator momentum without losing sight of the broader ecommerce business.'), CTA('Discuss a DTC TikTok Shop program with WEM →') ] },
    ],
    faqs: [
      { q: 'Should a DTC brand sell on TikTok Shop or its own website?', a: 'Most brands can use both. TikTok Shop can drive creator-led discovery and native checkout, while the DTC site remains important for the complete brand experience, CRM, subscriptions, bundles, and retention.' },
      { q: 'How do DTC brands get creators for TikTok Shop?', a: 'Brands can use Open and Target Collaboration, direct recruitment, agency relationships, and existing customer or community programs. Creator fit, content quality, response behavior, and product relevance matter more than follower count alone.' },
      { q: 'Can TikTok Shop content be reused on Meta, Amazon, or a DTC site?', a: 'Yes, when the brand has the applicable usage rights. Affiliate participation, commission, or a free sample does not automatically include paid ads, editing, Amazon, website, or long-term usage.' },
      { q: 'How many creator videos does a DTC brand need?', a: 'There is no universal number. The right volume depends on product complexity, creative diversity, budget, launch timing, and how quickly the brand needs to learn. MOONBREW used a high-volume Essentials layer plus a smaller Premium layer, but other brands may need a different mix.' },
      { q: 'What does WEM do for DTC brands?', a: 'WEM can manage TikTok Shop strategy, shop operations, creator recruitment, affiliate relationships, samples, brand-owned creator communities, content coaching, LIVE, GMV Max, and weekly performance decisions.' },
    ],
    related: [{ label: 'Amazon Sellers Expanding to TikTok Shop', href: 'amazon-sellers-expand-to-tiktok-shop.html' }, { label: 'TikTok Shop Creator Brief Template', href: 'tiktok-shop-creator-brief-template.html' }, { label: 'TikTok Shop Creator Affiliate Management', href: 'tiktok-shop-creator-affiliate-management.html' }],
  },
  zh: {
    meta: { title: 'DTC 品牌怎么用 TikTok Shop：从达人发现到跨渠道增长', cat: 'DTC · 达人电商', author: 'WE Marketing Team', date: '2026 年 3 月 18 日 · 2026 年 7 月 17 日更新', read: '12 分钟阅读', heroImage: 'hero-8-how-dtc-brands-use-tiktok-shop.png', heroAlt: 'DTC 品牌连接 TikTok Shop 达人、内容、商品页和跨渠道增长' },
    sections: [
      { id: '直接答案', h: 'TikTok Shop 对 DTC 品牌到底应该扮演什么角色？', body: [CALLOUT('TikTok Shop 应该是达人驱动的发现、成交和学习渠道，而不是独立站的替代品。成熟做法是一边承接站内成交，一边把达人内容跑出来的语言、场景和顾虑反哺到独立站、Amazon 和 Meta。'), P('DTC 团队本来就比较擅长品牌故事、商品组合、复购和用户反馈。TikTok Shop 新增加的是另一种增长机制：让许多达人用不同方式解释同一个商品，用户在刷到、理解和下单之间不需要离开平台。'), P('TikTok 在 2025 年 6 月公布，美国调研中 83% 的 TikTok Shop 消费者曾发现新产品，70% 曾发现新品牌。对已经有官网、但需要新受众和新内容角度的 DTC 品牌来说，这才是平台最关键的价值。')] },
      { id: '渠道分工', h: '不是 TikTok Shop 和独立站二选一，而是先把分工讲清楚', body: [TABLE(['渠道', '主要任务'], [['TikTok Shop', '达人发现、原生演示、affiliate 成交和快速内容学习'], ['独立站', '完整品牌体验、bundle、订阅、CRM 和复购'], ['Amazon', '高意图搜索、比较、零售信任和便利性'], ['Meta', '付费素材测试、retargeting、拓新和可控放量']]), P('渠道冲突通常不是因为平台太多，而是价格、bundle、库存和用户承诺各自为政。品牌需要一个统一活动日历和 offer architecture，让每个渠道有差异，但不会让老用户觉得吃亏。')] },
      { id: '准备度', h: 'DTC 品牌准备度要先看毛利和运营', body: [P('视觉做得好看，不代表已经适合上 TikTok Shop。品牌要先算清产品成本、履约、平台费用、折扣、affiliate 佣金、寄样、达人固定费用和付费放大之后的 contribution margin。'), UL(['先选 1 到 2 个最适合达人演示的 hero product', '确认美国库存、配送、退货和客服能力', '整理达人能快速理解的产品事实与 claim 边界', '决定佣金和 launch offer 可以使用多少毛利', '建立从样品审批、签收到发布和跟进的流程', '指定一个能连接达人、店铺、内容、库存和周度决定的负责人']), P('准备不是为了预测所有结果，而是避免把流量放大到一个还没有被验证的 offer 和履约系统里。')] },
      { id: '内容组合', h: '不要只追求一条完美广告，要建立 creator-content portfolio', body: [P('DTC 品牌通常已经有精致的品牌素材，但 TikTok Shop 还需要达人原生 proof：演示、routine、顾虑、比较、reaction 和具体使用场景。'), UL(['Essentials 内容负责铺量并测试更多真实角度', 'Premium 内容给重点概念更多策划、制作和 coaching', 'Affiliate 内容把达人表达直接连接到站内成交', '取得授权以后，优胜内容可以进入 Meta、Amazon 和独立站', 'Content coaching 提升准确度和完成度，但不抹掉达人自己的声音']), P('品牌很难在会议室里提前选出 winning hook。只有足够多的真实市场测试，才能看清哪一种受众、痛点、proof 和 offer 组合更有效。')] },
      { id: 'moonbrew', h: 'MOONBREW：已有 Amazon 和独立站基础，怎么做 TikTok Shop 新品冷启动？', body: [P('MOONBREW 在 Amazon 和独立站已经有比较成熟的 presence，所以这不是品牌从零开始，而是平台冷启动。进入 TikTok Shop 后，原生内容、达人关系、新 listing 和 launch 节奏仍然要重新建立。'), P('WEM 围绕新 flavor 和新 listing 设计两层内容：200 条 Essentials 视频负责铺量和建立品牌 presence，10 条 Premium 视频负责提高创意上限。两条突出视频达到 1.2M+ 和 828K 播放，其中一条帮助新 flavor 与新 listing 完成冷启动。'), P('对 DTC 品牌来说，这个案例说明：已有品牌基础会改善起点，但不能替代平台执行。内容数量带来学习，高质量创意带来 breakout potential，店铺与达人运营则负责把信号接成 launch system。'), CTA('了解 WEM Creator Content 服务 →', '/services/creator-content.html') ] },
      { id: '达人社群', h: '把一次性达人邀约变成品牌自己的达人社群', body: [P('当品牌不再把每个达人当作一次性交易，而是持续识别适配、支持内容、复合作并参与新品，达人关系才会变成更耐用的资产。'), UL(['按品类、受众、内容和合作行为筛选，不只看粉丝量', '记录寄样与沟通历史，避免重复、机械式 outreach', '让合适达人更早接触新品和产品教育', '需要高质量交付时加入 content review 和 training call', '把达人问题沉淀成商品页和 FAQ 输入', '把 affiliate 佣金、flat fee 和内容使用权分开约定']), P('WEM 的活跃 8,000+ TikTok Shop affiliate / creator 社群可以帮助品牌更快完成 cold start；同时，WEM 也会帮助品牌招募和管理属于自己的达人社群，让关系与学习长期留在品牌内部。')] },
      { id: '每周复盘', h: '每周把内容、店铺和其他渠道放在一起复盘', body: [TABLE(['观察到的信号', '可能的下一步'], [['某个 hook 持续抓住注意力', '测试到 TikTok listing、独立站、Amazon PDP 或 Meta 素材'], ['达人反复提出同一顾虑', '调整商品页、brief、FAQ、包装或 claims 指南'], ['一个 SKU 明显优于其他商品', '集中寄样、内容、库存和付费放大'], ['播放上升但转化不动', '检查受众、价格、offer、页面、评价和配送预期'], ['某达人持续稳定交付', '安排复合作、新品优先或单独谈付费 scope']]), P('跨渠道提升要谨慎衡量。品牌搜索、独立站流量、Amazon 需求和 Meta 素材表现可能与 TikTok 同时变化，但不能把相关性写成保证归因。')] },
      { id: 'wem', h: 'WEM 怎么帮助 DTC 品牌运营 TikTok Shop？', body: [P('WE Marketing (WEM) 是 official TikTok Shop Partner agency，也是 full-service management partner。WEM 会把达人联盟、creator content、寄样、达人社群、商品页、直播、GMV Max、用户体验和数据复盘连成一套，而不是交给互不沟通的供应商。'), UL(['美国本土团队，支持英文、普通话、西班牙语和广东话，并在适合场景提供繁体中文支持', '活跃的 8,000+ TikTok Shop affiliate / creator 社群', '依靠成熟达人关系支持 cold start 和新品 launch', '帮品牌招募并长期管理自己的达人社群', 'Content coach 提供 review、feedback 和 training call', '连接店铺、直播、paid amplification 和跨渠道复盘']), P('当 DTC 品牌已经有产品和客户基础，但缺少一支能建立 TikTok 原生达人 momentum、又能照顾完整电商盘子的运营团队时，WEM 最能发挥作用。'), CTA('和 WEM 讨论 DTC TikTok Shop 运营方案 →') ] },
    ],
    faqs: [
      { q: 'DTC 品牌应该做 TikTok Shop，还是只做独立站？', a: '多数品牌可以同时做。TikTok Shop 负责达人发现和站内成交，独立站继续负责完整品牌体验、CRM、订阅、bundle 和复购。' },
      { q: 'DTC 品牌怎么找 TikTok Shop 达人？', a: '可以通过 Open/Target Collaboration、主动招募、agency 社群和现有用户社群寻找。判断时应看品类适配、内容质量、沟通和合作行为，而不只看粉丝量。' },
      { q: 'TikTok Shop 达人内容可以放到 Meta、Amazon 或独立站吗？', a: '取得相应使用权后可以。Affiliate、佣金或免费样品不会自动包含付费广告、剪辑、Amazon、官网或长期使用权。' },
      { q: 'DTC 品牌需要多少条达人视频？', a: '没有统一答案，要看产品复杂度、角度数量、预算和 launch 时间。MOONBREW 使用了高数量 Essentials 加小规模 Premium 的组合，其他品牌应该按自己的目标设计。' },
      { q: 'WEM 能为 DTC 品牌做什么？', a: 'WEM 可以负责 TikTok Shop 策略、店铺运营、达人招募、affiliate、寄样、品牌达人社群、content coaching、直播、GMV Max 和每周商业复盘。' },
    ],
    related: [{ label: 'Amazon 卖家拓展 TikTok Shop', href: 'amazon-sellers-expand-to-tiktok-shop.html?lang=zh' }, { label: 'TikTok Shop 达人 Brief 模板', href: 'tiktok-shop-creator-brief-template.html?lang=zh' }, { label: 'TikTok Shop 达人联盟管理', href: 'tiktok-shop-creator-affiliate-management.html?lang=zh' }],
  }
};

function App() { const [lang, setLang] = useState(() => { const x = new URLSearchParams(window.location.search).get('lang'); if (x === 'zh' || x === 'en') return x; return localStorage.getItem('we-lang') || 'en'; }); const post = POSTS[lang]; useEffect(() => { localStorage.setItem('we-lang', lang); document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en'; document.title = `${post.meta.title} | WE Marketing`; }, [lang, post]); useEffect(() => { if (window.lucide) window.lucide.createIcons(); }); return <div data-screen-label="WE Blog · DTC Brands"><CursorStars /><NavBar lang={lang} onLang={setLang} basePath="../" /><BlogPost {...post} labels={LABELS[lang]} /><CtaFooter lang={lang} /><Footer lang={lang} basePath="../" /></div>; }
ReactDOM.createRoot(document.getElementById('root')).render(<App />);
