const { useState, useEffect } = React;
const P = (text) => ({ kind: 'p', text });
const UL = (items) => ({ kind: 'list', items });
const TABLE = (headers, rows) => ({ kind: 'table', headers, rows });
const CALLOUT = (text) => ({ kind: 'callout', text });
const CTA = (label, href = 'https://zus03h0enw04.sg.larksuite.com/scheduler/03970278dd9a7925') => ({ kind: 'cta', label, href });
const LABELS = { en: { back: 'Blog', toc: 'On this page', faq: 'Frequently asked questions', related: 'Related guides' }, zh: { back: '博客', toc: '本文目录', faq: '常见问题', related: '相关文章' } };

const POSTS = {
  en: {
    meta: { title: 'TikTok Shop Agency vs. In-House Team: How Brands Should Decide', cat: 'TEAM · DECISION GUIDE', author: 'WE Marketing Team', date: 'Jan 29, 2026', read: '11 min read', heroImage: 'hero-tiktok-shop-agency-vs-in-house.png', heroAlt: 'TikTok Shop agency versus in-house team decision framework' },
    sections: [
      { id: 'direct-answer', h: 'Should you hire a TikTok Shop agency or build an in-house team?', body: [CALLOUT('Hire in-house when TikTok Shop is a long-term core channel and the brand can staff daily ownership across shop operations, creators, samples, content, LIVE, paid growth, customer experience, and reporting. Hire an agency when speed, specialist experience, creator operations, or cross-functional execution is the immediate constraint. Many brands ultimately use a hybrid model.'), P('The decision is not simply payroll versus agency fee. TikTok Shop is a creator-commerce operating system. The brand has to decide who owns each recurring job, how quickly the team can learn, and whether one person can realistically coordinate every dependency.'), P('WE Marketing is an official TikTok Shop Partner agency and a full-service management partner. WEM can operate the full workflow or work with an internal brand lead, ecommerce team, creative team, warehouse, and customer-service team. The right scope depends on what the brand already does well and where execution repeatedly breaks.') ] },
      { id: 'work', h: 'List the work before choosing the team model', body: [P('A brand can make a poor hiring decision when it defines the role too narrowly. “TikTok Shop manager” may sound like one job, but the work often crosses several functions with different daily rhythms.'), TABLE(['Workstream', 'Recurring ownership'], [['Shop operations', 'Catalog, product pages, offers, campaigns, inventory signals, account health, and issue follow-up'], ['Creator affiliate', 'Product selection, Open and Target Collaboration, creator outreach, samples, communication, and repeat partnerships'], ['Content', 'Briefs, feedback, UGC pipeline, rights review, and learning by hook or format'], ['LIVE', 'Host or creator plan, products, offers, scripts, moderation, operations, and post-LIVE review'], ['Paid growth', 'GMV Max or other applicable paid programs, creative selection, budget decisions, and coordination with organic signals'], ['Customer experience', 'Shipping expectations, reviews, questions, returns, and recurring product objections'], ['Reporting', 'Performance, blockers, owners, decisions, and next actions—not only a dashboard export']]), P('Once this map is visible, the brand can choose which responsibilities belong internally and which require outside operating support.') ] },
      { id: 'in-house', h: 'When an in-house TikTok Shop team makes sense', body: [P('An internal team is strongest when TikTok Shop is strategically important, the brand expects to operate it for years, and leadership is willing to build dedicated roles rather than add the channel to someone’s existing workload.'), UL(['The brand has a clear internal owner with decision authority', 'Product, inventory, pricing, compliance, and customer-service information are easy to access', 'The team can maintain daily creator and sample follow-up', 'Creative production and LIVE operations have real capacity', 'Paid and organic decisions can share data and learning', 'Leadership accepts that hiring and training take time']), P('In-house ownership can also protect institutional knowledge. The risk is under-staffing: one person becomes responsible for the shop, creators, content, ads, customer questions, and executive reporting, and the channel turns into reactive task management.') ] },
      { id: 'agency', h: 'When a TikTok Shop agency is the better fit', body: [P('An agency is useful when the brand needs to launch or repair the operating system faster than it can recruit and train a full team. It can also fill a specialist gap while the internal team retains product knowledge and final business decisions.'), UL(['The shop is live but creator outreach and follow-up are inconsistent', 'Samples are being shipped without enough visibility or learning', 'The team needs U.S. creator relationships or bilingual execution', 'Content, shop operations, LIVE, and paid growth are managed in separate silos', 'The brand needs a repeatable weekly operating cadence', 'Leadership needs one accountable partner across multiple workstreams']), P('Agency fit still matters. Brands should ask who does the daily work, what is included, which decisions remain with the brand, how creator communication is handled, and what the weekly report is expected to change.') ] },
      { id: 'hybrid', h: 'A hybrid model is often the most practical', body: [P('The hybrid model keeps brand truth and business authority in-house while using an agency for specialized execution and operating capacity. It avoids outsourcing every decision and avoids forcing an internal generalist to build every system alone.'), TABLE(['Brand owns', 'Agency can own or support'], [['Product truth, margin, inventory priorities, and business goals', 'Shop setup, operating cadence, and product-page execution'], ['Final claim, legal, and brand approvals', 'Creator sourcing, affiliate management, samples, and follow-up'], ['Customer and product knowledge', 'Brief structure, UGC feedback, LIVE support, and content learning'], ['Budget approval and internal stakeholder alignment', 'GMV Max management, reporting, blockers, and recommended next actions']]), P('WEM uses this model with brands that already have capable ecommerce or marketing teams but need a dedicated TikTok Shop operating layer. Responsibilities should be written down by workstream, decision, owner, and response time.') ] },
      { id: 'compare', h: 'How to compare the real cost', body: [P('Do not compare an agency proposal with one employee salary. Compare complete operating coverage. An internal model may require management, creator operations, content, LIVE, paid media, analytics, and tools. An agency model may exclude ad spend, samples, creator fees, production, or LIVE talent. The same label can hide very different scopes.'), UL(['Map every recurring task and its expected frequency', 'Separate management fees from media, samples, commissions, creator fees, production, and usage rights', 'Include recruiting, onboarding, management time, and coverage risk for internal roles', 'Ask which deliverables are outputs and which are business decisions', 'Define attribution and performance-fee terms before signing']), P('WEM publishes its pricing approach separately so brands can compare scope rather than guess. The agency-versus-in-house decision should still start with ownership and capability, not the cheapest visible line item.') ] },
      { id: 'wem', h: 'How WEM works with internal brand teams', body: [P('WEM is not a detached creator vendor. As an official TikTok Shop Partner agency and full-service management partner, WE Marketing connects creator affiliate management, creator-community operations, sample coordination, content coaching, LIVE, shop operations, GMV Max, and weekly commercial review.'), UL(['A U.S.-based team supporting English and Spanish', 'An active community of 8,000+ TikTok Shop affiliates and creators', 'Creator recruitment and community management for brands building a creator network of their own', 'Cold-start and new-product-launch activation supported by existing creator relationships', 'Content coaches providing review, feedback, and training calls', 'One feedback loop from creator questions to briefs, product pages, offers, and paid creative', 'Flexible division of work around the brand’s ecommerce, content, warehouse, and support teams']), P('A brand should consider WEM when it has product and ambition but lacks the operating layer to connect creator discovery with consistent commerce execution.'), P('For ANANKECLO, a men’s fashion brand, WEM supported a true zero-to-one cold start: building the creator motion, establishing a hero listing, and helping a breakout creator video create momentum. It is a practical example of when a full-service partner can connect the work faster than isolated vendors.'), CTA('See the ANANKECLO cold-start showcase →', '/showcase.html#case-fashion-cold-start'), CTA('Discuss the right team model with WEM →') ] },
      { id: 'decision-checklist', h: 'A decision checklist for brand leaders', body: [P('Before choosing a model, answer the following questions honestly. A “no” does not always mean hire an agency; it identifies the capability that must be built or supported.'), UL(['Who owns TikTok Shop every day?', 'Who can approve products, offers, claims, inventory, creator exceptions, and paid budgets?', 'Who recruits and follows up with creators after the first invitation?', 'Who tracks samples from approval through content and next action?', 'Who translates content learning into listing and offer changes?', 'Who runs or coordinates LIVE?', 'Who decides which content is suitable for licensing or paid amplification?', 'Can the team review results and make decisions every week?']), P('The right model is the one that leaves no critical workflow without an owner. Titles matter less than clear responsibility and operating capacity.') ] },
    ],
    faqs: [
      { q: 'Is it better to hire a TikTok Shop agency or an employee?', a: 'It depends on scope and timing. An employee can build long-term internal ownership, while an agency can provide faster specialist capacity across creators, shop operations, content, LIVE, and paid growth. Compare full operating coverage, not one salary against one retainer.' },
      { q: 'What does a TikTok Shop agency do?', a: 'A full-service TikTok Shop agency can support shop operations, creator affiliate management, samples, UGC, LIVE, product pages, paid growth, reporting, and weekly optimization. Exact scope should be defined in the proposal.' },
      { q: 'Can a brand use both an in-house team and a TikTok Shop agency?', a: 'Yes. A hybrid model often keeps product knowledge, approvals, and business decisions in-house while the agency provides specialized execution, creator operations, and platform management.' },
      { q: 'When should a brand bring TikTok Shop in-house?', a: 'In-house ownership makes sense when the channel is strategically important, leadership will fund dedicated roles, and the team can maintain daily execution across shop, creators, samples, content, LIVE, paid growth, and reporting.' },
      { q: 'How does WEM work with in-house teams?', a: 'WEM defines ownership by workstream and can operate creator affiliate management, samples, creator-community relationships, shop operations, content feedback, LIVE, GMV Max, and reporting while the internal team retains product, budget, and brand decisions.' },
    ],
    related: [{ label: 'TikTok Shop Agency Cost Guide', href: 'tiktok-shop-agency-cost-guide.html' }, { label: 'What Does a TikTok Shop Agency Do?', href: 'what-does-a-tiktok-shop-agency-do.html' }, { label: 'TikTok Shop Creator Affiliate Management', href: 'tiktok-shop-creator-affiliate-management.html' }],
  },
  zh: {
    meta: { title: 'TikTok Shop 找 Agency 还是自己招团队？品牌决策指南', cat: '团队 · 决策指南', author: 'WE Marketing Team', date: '2026 年 1 月 29 日', read: '12 分钟阅读', heroImage: 'hero-tiktok-shop-agency-vs-in-house.png', heroAlt: 'TikTok Shop agency 与内部团队分工判断框架' },
    sections: [
      { id: '直接答案', h: 'TikTok Shop 应该找 agency，还是自己招团队？', body: [CALLOUT('如果 TikTok Shop 是长期核心渠道，而且品牌愿意配置专人负责店铺、达人、寄样、内容、直播、付费增长、用户体验和数据复盘，可以逐步搭建内部团队。如果当前瓶颈是上线速度、专业经验、达人运营或跨团队执行，agency 更合适。很多品牌最终会采用混合模式。'), P('这不是“员工工资和 agency 月费谁更便宜”的简单比较。TikTok Shop 是一套 creator-commerce 运营系统，品牌要先决定每项日常工作谁负责、团队需要多快形成学习、一个人是否真的能覆盖所有环节。'), P('WE Marketing 是 official TikTok Shop Partner agency，也是 full-service management partner。WEM 可以承担完整运营，也可以和品牌内部的电商、内容、仓库、客服和管理团队协作。')] },
      { id: '先列工作', h: '先把所有工作列出来，再选团队模式', body: [P('很多品牌把岗位定义得太窄。“TikTok Shop 运营”听起来像一个职位，实际却横跨多个节奏完全不同的职能。'), TABLE(['模块', '需要持续负责什么'], [['店铺运营', '商品、页面、offer、活动、库存信号、店铺健康和问题跟进'], ['达人联盟', '选品、Open/Target Collaboration、邀约、寄样、沟通和复合作'], ['内容', 'brief、反馈、UGC、权利审核和 hook/格式学习'], ['直播', '主播或达人、产品、offer、脚本、场控和复盘'], ['付费增长', 'GMV Max 或适用的广告项目、素材和预算决策'], ['用户体验', '物流预期、评论、问题、退款和重复顾虑'], ['数据复盘', '结果、卡点、负责人、决定和下一步，而不是只导出报表']]), P('把这张责任地图画出来以后，品牌才知道哪些能力应该内部掌握，哪些需要外部运营支持。')] },
      { id: '适合内部团队', h: '什么情况下适合搭建内部团队？', body: [P('当 TikTok Shop 对品牌长期重要，而且管理层愿意配置真正的专职岗位，而不是把渠道塞给现有员工兼任时，内部团队更有优势。'), UL(['有一个能做决定的内部负责人', '产品、库存、价格、合规和客服信息容易获得', '团队可以每天跟进达人和寄样', '内容制作与直播有真实产能', '付费和自然内容可以共享数据与学习', '管理层接受招聘和培养需要时间']), P('内部团队的优势是知识沉淀。风险是配置不足：一个人同时承担店铺、达人、内容、广告、客服和管理层汇报，最后只能被动救火。')] },
      { id: '适合agency', h: '什么情况下更适合找 TikTok Shop agency？', body: [P('如果品牌需要比招聘完整团队更快地上线或修复运营系统，agency 更适合。它也可以补上专业能力缺口，让内部团队继续掌握产品和最终商业决定。'), UL(['店铺已经上线，但达人邀约和跟进不稳定', '寄出很多样品，却看不清后续内容和学习', '需要美国达人关系或中英文双语执行', '内容、店铺、直播和付费由不同团队割裂管理', '需要稳定的每周运营节奏', '管理层希望一个伙伴对多个环节负责']), P('选 agency 时仍然要问清楚：每天谁做事、范围包括什么、哪些决定留给品牌、达人沟通怎么管理、周报要推动什么改变。')] },
      { id: '混合模式', h: '混合模式通常更实际', body: [P('混合模式把品牌事实和商业决策留在内部，把专业执行和额外产能交给 agency。这样既不会把所有决定外包，也不会要求一个内部通才从零建立全部系统。'), TABLE(['品牌内部负责', 'Agency 可以负责或支持'], [['产品事实、毛利、库存优先级和目标', '店铺运营节奏与商品页执行'], ['最终 claims、法务和品牌审批', '达人筛选、affiliate、寄样和跟进'], ['客户与产品知识', 'brief、UGC 反馈、直播和内容学习'], ['预算批准和内部协调', 'GMV Max、数据复盘、卡点与下一步建议']]), P('WEM 会按 workstream、decision、owner 和 response time 把分工写清楚，特别适合已经有电商或营销团队、但缺少 TikTok Shop 专职运营层的品牌。')] },
      { id: '比较成本', h: '怎么比较真实成本？', body: [P('不要拿 agency proposal 和一个员工工资直接比较。内部模式可能需要运营、达人、内容、直播、广告、分析和工具；agency 报价也可能不包括广告费、样品、达人固定费用、制作或直播主播。'), UL(['列出所有日常任务和频率', '把管理费与广告、样品、佣金、达人费用、制作和使用权分开', '内部团队要计算招聘、培训、管理和人员空缺风险', '问清交付物是“做了什么”，还是“推动了什么决定”', '签约前确认归因口径和 performance fee 条款']), P('WEM 另有公开的 agency cost guide，帮助品牌按 scope 比较。但最终决策仍然应该从责任和能力开始。')] },
      { id: 'wem协作', h: 'WEM 怎么和品牌内部团队协作？', body: [P('WEM 不是单独提供达人名单的供应商。作为 official TikTok Shop Partner agency 和 full-service management partner，WE Marketing 可以连接达人联盟、达人私域、寄样、content coaching、直播、店铺运营、GMV Max 和周度商业复盘。'), UL(['美国本土团队，可用英文、普通话、西班牙语和广东话沟通，并在适合的场景提供繁体中文支持', '活跃的 8,000+ TikTok Shop affiliate / creator 社群', '为品牌招募达人，并帮助品牌建立与管理自己的达人社群', '依靠现有达人关系支持 cold start 与新品起盘，但不承诺保证销量', 'Content coach 提供内容审核、反馈和 training call', '把达人问题反馈到 brief、商品页、offer 和付费素材', '围绕品牌现有的电商、内容、仓库与客服团队灵活分工']), P('当品牌有好产品和增长目标，却缺少一层把达人发现和电商执行连起来的运营系统时，就适合找 WEM。'), P('ANANKECLO 是一个美国男装 cold-start 案例。WEM 从 0 到 1 帮品牌建立达人动作、形成 hero listing，并通过爆款达人视频带动起盘。它说明 full-service partner 的价值，是把分散的工作更快连接起来。'), CTA('查看 ANANKECLO 冷启动案例 →', '/showcase.html#case-fashion-cold-start'), CTA('和 WEM 讨论团队模式 →')] },
      { id: '决策清单', h: '品牌负责人可以先回答这 8 个问题', body: [P('下面任何一个问题答不上来，都说明有一项能力需要建立或补充，不代表一定要找 agency。'), UL(['谁每天对 TikTok Shop 负责？', '谁能批准商品、offer、claims、库存例外和广告预算？', '谁在发出邀请以后继续跟达人？', '谁从样品审批一直追踪到内容与下一步？', '谁把内容学习转成商品页和 offer 调整？', '谁负责直播或协调直播？', '谁判断内容能否授权或进入付费放大？', '团队能否每周复盘并做出决定？']), P('正确的模式，是没有关键流程处于无人负责状态。岗位名称没有清楚的责任和产能重要。')] },
    ],
    faqs: [
      { q: 'TikTok Shop 找 agency 好，还是自己招人好？', a: '如果品牌希望长期沉淀内部能力，并愿意配置专职团队，可以自己招人；如果需要更快上线、专业执行、达人关系或跨模块协同，agency 更合适。应该比较完整运营覆盖，而不是只比较一份工资和一个月费。' },
      { q: 'TikTok Shop agency 一般负责什么？', a: '全服务 agency 可以负责店铺运营、达人联盟、寄样、UGC、直播、商品页、付费增长、数据复盘和持续优化，具体范围要在 proposal 中写清楚。' },
      { q: '品牌可以同时有内部团队和 TikTok Shop agency 吗？', a: '可以。混合模式可以把产品知识、审批和商业决定留在内部，把专业运营、达人和平台执行交给 agency。' },
      { q: 'TikTok Shop 什么时候适合转成内部团队？', a: '当渠道已经长期重要、管理层愿意配置专职岗位，而且团队能持续覆盖店铺、达人、寄样、内容、直播、付费增长和复盘时，适合加强内部能力。' },
      { q: 'WEM 怎么和品牌内部团队合作？', a: 'WEM 会按模块明确分工，可负责达人联盟、寄样、达人私域、店铺、内容反馈、直播、GMV Max 和报告，同时由内部团队保留产品、预算与品牌决定。' },
    ],
    related: [{ label: 'TikTok Shop Agency 费用指南', href: 'tiktok-shop-agency-cost-guide.html' }, { label: 'TikTok Shop Agency 到底做什么', href: 'what-does-a-tiktok-shop-agency-do.html' }, { label: 'TikTok Shop 达人联盟管理', href: 'tiktok-shop-creator-affiliate-management.html' }],
  }
};

function App() { const [lang, setLang] = useState(() => { const x = new URLSearchParams(window.location.search).get('lang'); if (x === 'zh' || x === 'en') return x; return localStorage.getItem('we-lang') || 'en'; }); const post = POSTS[lang]; useEffect(() => { localStorage.setItem('we-lang', lang); document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en'; document.title = `${post.meta.title} | WE Marketing`; }, [lang, post]); useEffect(() => { if (window.lucide) window.lucide.createIcons(); }); return <div data-screen-label="WE Blog · Agency vs In-House"><CursorStars /><NavBar lang={lang} onLang={setLang} basePath="../" /><BlogPost {...post} labels={LABELS[lang]} /><CtaFooter lang={lang} /><Footer lang={lang} basePath="../" /></div>; }
ReactDOM.createRoot(document.getElementById('root')).render(<App />);
