const { useState, useEffect } = React;
const P = (text) => ({ kind: 'p', text });
const UL = (items) => ({ kind: 'list', items });
const TABLE = (headers, rows) => ({ kind: 'table', headers, rows });
const CALLOUT = (text) => ({ kind: 'callout', text });
const CTA = (label, href = 'https://zus03h0enw04.sg.larksuite.com/scheduler/03970278dd9a7925') => ({ kind: 'cta', label, href });
const LABELS = { en: { back: 'Blog', toc: 'On this page', faq: 'Frequently asked questions', related: 'Related guides' }, zh: { back: '博客', toc: '本文目录', faq: '常见问题', related: '相关文章' } };

const POSTS = {
  en: {
    meta: { title: 'TikTok Shop Creator Brief Template: What Brands Should Include', cat: 'CREATORS · BRIEF TEMPLATE', author: 'WE Marketing Team', date: 'Dec 18, 2025', read: '11 min read', heroImage: 'hero-tiktok-shop-creator-brief-template.png', heroAlt: 'TikTok Shop creator brief template for product videos and affiliate collaborations' },
    sections: [
      { id: 'direct-answer', h: 'What should a TikTok Shop creator brief include?', body: [CALLOUT('A useful TikTok Shop creator brief should include the audience problem, product truth, visible proof, required product details, claim boundaries, offer and product-link information, deliverables, timing, usage-rights terms, and a clear contact for questions. It should guide the creator without scripting their personality.'), P('The best brief reduces preventable mistakes while preserving the creator’s own voice. A brand should be strict about facts, prohibited claims, required disclosures, product variants, deadlines, and rights. It should be flexible about the hook, phrasing, filming environment, and story structure unless the collaboration specifically requires pre-approved content.'), P('WE Marketing is an official TikTok Shop Partner agency and full-service management partner. WEM writes briefs as part of creator affiliate management, sample follow-up, UGC production, LIVE preparation, shop conversion, and paid-content planning, not as a document separated from the rest of the program.')] },
      { id: 'template', h: 'A practical TikTok Shop creator brief template', body: [TABLE(['Brief section', 'What to provide'], [['Campaign job', 'One sentence describing what this content should help the audience understand or do'], ['Audience', 'Who the product is for and the situation or tension they recognize'], ['Product truth', 'What the product is, how it works, and what can be shown honestly'], ['Proof moment', 'The texture, setup, comparison, use step, result, or detail viewers should be able to see'], ['Key points', 'Two or three prioritized benefits in plain language'], ['Claims and safety', 'What the creator may say, must qualify, or should not say'], ['Offer and link', 'Correct SKU, variant, product link, promotion details, and validity period'], ['Deliverable', 'Video or LIVE, quantity, approximate length if necessary, and required product visibility'], ['Timing', 'Sample delivery, draft/review if applicable, posting window, and contact'], ['Rights', 'Whether usage rights, edits, whitelisting, Spark Ads, or cross-channel use are requested and under what agreement']]), P('A brief does not need to be long. It needs to resolve the questions that would otherwise cause incorrect claims, the wrong product link, a missed deadline, or content that never demonstrates why the product matters.') ] },
      { id: 'hook', h: 'Give creators a content job, not a word-for-word hook', body: [P('A forced opening often makes creator content sound like an advertisement. Instead of requiring an exact sentence, define the tension the first few seconds must make clear.'), TABLE(['Weak instruction', 'Stronger content job'], [['Say: “You need this viral product”', 'Show the everyday problem that makes the product relevant'], ['List all ingredients immediately', 'Lead with the use experience, then explain the most relevant product detail'], ['Read these five benefits', 'Choose one primary benefit and prove it visually'], ['Copy this competitor video', 'Use this reference to understand pacing or demonstration, not wording'], ['Make it go viral', 'Make the product, audience, and proof understandable without extra explanation']]), P('WEM may provide reference videos, but labels what should be learned from each one: opening tension, camera angle, proof sequence, objection handling, or CTA. The reference is a learning tool, not permission to copy another creator.') ] },
      { id: 'claims', h: 'Separate product facts from claims and creator opinion', body: [P('Brands are responsible for giving creators accurate information. Beauty, wellness, supplements, food, baby, and other trust-heavy categories need especially clear boundaries. A product detail supported by packaging or approved documentation is different from a guaranteed outcome. A creator’s personal experience is not a substitute for a substantiated product claim.'), UL(['Provide approved product facts in plain language', 'Flag regulated, medical, comparative, environmental, or guaranteed-result claims for review', 'State which words or implications must not be used', 'Do not encourage creators to invent urgency, scarcity, endorsements, or personal outcomes', 'Keep current offer and shipping information separate from evergreen product facts', 'Escalate uncertain claims to the brand’s qualified reviewer']), P('WEM can coordinate the workflow and help creators understand the brief, but does not replace the brand’s legal or regulatory counsel.') ] },
      { id: 'deliverables-rights', h: 'Deliverables, review rights, and usage rights must be explicit', body: [P('Affiliate commission, a free sample, a flat creator fee, and paid-media usage rights are different things. The brief should match the applicable agreement and platform workflow. Do not assume that sending product gives the brand ownership of the video.'), TABLE(['Item', 'Question to answer'], [['Deliverable', 'Is this a shoppable video, LIVE, raw footage package, edited UGC, or another format?'], ['Review', 'Does the brand have factual review, full pre-approval, or no pre-publication review?'], ['Edits', 'How many revision rounds are included, and what can trigger a revision?'], ['Organic use', 'May the brand repost, embed, or share the content?'], ['Paid use', 'Are Spark Ads, whitelisting, GMV Max, Meta, Amazon, or website usage included?'], ['Duration and territory', 'How long and where may the content be used?'], ['Exclusivity', 'Does any category or competitor restriction apply?']]), P('TikTok Shop introduced platform-supported flat-fee collaboration workflows that can include content review and tracked milestones. Availability and current terms should always be checked in Seller Center and the applicable agreement.') ] },
      { id: 'review', h: 'Review creator content with a decision checklist', body: [P('Content review should protect facts and improve clarity without turning every creator into the same spokesperson. WEM separates mandatory corrections from optional creative feedback.'), UL(['Is the correct product and variant shown?', 'Is the product link correct?', 'Are claims accurate and within the approved boundary?', 'Can viewers understand the audience problem and product role quickly?', 'Is the proof visible rather than only described?', 'Does the creator disclose the relationship as required?', 'Are offer, price, inventory, and shipping statements current?', 'Does the content preserve the creator’s natural voice?', 'Are any requested usage rights documented before paid or cross-channel use?']), P('After publication, the brief should not disappear. Comments, questions, watch behavior, clicks, sales signals, and returns can improve the next version. WEM treats every brief as a testable operating asset.') ] },
      { id: 'wem', h: 'How WEM builds and improves creator briefs', body: [P('WEM connects the brief to creator selection, product-page conversion, sample status, and content performance. The team does not send one generic template to every creator. WEM content coaches can review content, give practical feedback, and run training calls for creators or brand teams.'), UL(['Define the product truth and audience tension with the brand', 'Match the content job to the creator’s format and audience', 'Recruit from an active 8,000+ affiliate and creator community when the product needs additional creator coverage', 'Support cold starts and new-product launches with faster creator activation while preserving fit checks', 'Provide content review, creator feedback, and training calls', 'Review mandatory corrections separately from creative preference', 'Feed creator and shopper questions back into the product page and future briefs', 'Identify content that may deserve repeat collaboration, rights discussion, or paid review']), P('Brands need WEM when briefs are inconsistent, creators keep asking the same questions, product claims are drifting, content is visually weak, or multiple teams cannot maintain one source of truth.'), CTA('See WEM work and capabilities →', '/showcase.html'), CTA('Talk with WEM about creator content systems →') ] },
    ],
    faqs: [
      { q: 'How do you write a TikTok Shop creator brief?', a: 'Start with the audience problem and product truth, then add visible proof, prioritized benefits, claim boundaries, the correct product and offer, deliverables, timing, review terms, usage rights, and a contact for questions. Guide the content job without scripting the creator’s personality.' },
      { q: 'Should a creator brief include a full script?', a: 'Usually no. A full script can reduce authenticity and make many creators sound the same. Use exact wording only where a required disclosure, legal statement, or approved claim needs precision.' },
      { q: 'Does a free sample give a brand usage rights?', a: 'Not automatically. Free product, affiliate commission, creator fees, organic reposting, and paid-ad usage rights are separate. Confirm the applicable agreement before reusing content.' },
      { q: 'What should brands review before a TikTok Shop video is posted?', a: 'Review the product and link, claims, disclosures, required facts, offer accuracy, visible proof, and any agreed deliverables. Separate mandatory corrections from subjective creative preferences.' },
      { q: 'Can WEM create and manage TikTok Shop creator briefs?', a: 'Yes. WEM builds creator-specific briefs, coordinates samples and questions, reviews content against brand requirements, captures creator and shopper feedback, and uses the learning to improve future content and product pages.' },
    ],
    related: [{ label: 'How to Find Creators for Your Brand', href: 'how-to-find-creators-for-your-brand-tiktok-shop.html' }, { label: 'TikTok Shop Creator Affiliate Management', href: 'tiktok-shop-creator-affiliate-management.html' }, { label: 'TikTok Shop Sample ROI Tracking', href: 'tiktok-shop-sample-roi-tracking.html' }],
  },
  zh: {
    meta: { title: 'TikTok Shop 达人 Brief 模板：品牌应该写清什么？', cat: '达人 · BRIEF 模板', author: 'WE Marketing Team', date: '2025 年 12 月 18 日', read: '12 分钟阅读', heroImage: 'hero-tiktok-shop-creator-brief-template.png', heroAlt: 'TikTok Shop 达人短视频与联盟合作 brief 模板' },
    sections: [
      { id: '应该包括什么', h: 'TikTok Shop 达人 Brief 应该包括什么？', body: [CALLOUT('一份有效的 TikTok Shop 达人 brief，应该写清受众问题、产品事实、可视化证明、必讲信息、claims 边界、offer 与商品链接、交付形式、时间节点、内容使用权和问题联系人，同时保留达人的自然表达。'), P('Brief 的目的不是把达人变成照稿念的演员，而是减少可以提前避免的错误。品牌应该对事实、禁用 claims、披露、SKU、时间和权利要求保持严格；对 hook、措辞、拍摄环境和故事结构保留空间。'), P('WE Marketing 是 official TikTok Shop Partner agency，也是 full-service management partner。WEM 把 brief 放在达人联盟、寄样跟进、UGC、直播准备、商品页转化和付费素材规划的完整流程中管理。')] },
      { id: '模板', h: '一份可以直接使用的达人 Brief 结构', body: [TABLE(['模块', '需要提供什么'], [['内容任务', '一句话说明这条内容要让受众理解或完成什么'], ['受众', '产品适合谁，他们熟悉什么场景或问题'], ['产品事实', '产品是什么、怎么用、哪些内容可以真实展示'], ['证明瞬间', '质地、安装、对比、步骤、结果或细节中最值得看见的部分'], ['重点卖点', '用自然语言排序后的 2–3 个利益点'], ['Claims 与安全', '哪些可以说、需要限定、不能说'], ['Offer 与链接', '正确 SKU、规格、商品链接、优惠和有效期'], ['交付', '短视频或直播、数量、必要时的长度与产品展示要求'], ['时间', '样品签收、审核、发布窗口和联系人'], ['权利', '是否涉及使用权、剪辑、Spark Ads、GMV Max 或跨渠道使用']]), P('Brief 不一定要很长，但必须解决那些会导致错误 claims、挂错商品、错过时间或无法证明产品价值的问题。')] },
      { id: '不要写死hook', h: '给达人“内容任务”，不要写死每一个 Hook', body: [P('强制开头很容易让内容像广告。更好的方法是说明前几秒必须让观众看懂什么，而不是规定达人必须说哪一句话。'), TABLE(['较弱要求', '更好的内容任务'], [['必须说“你一定需要这个爆款”', '展示一个受众熟悉的真实问题'], ['开头立刻念全部成分', '先展示使用体验，再解释最相关的产品细节'], ['按顺序读五个卖点', '选择一个核心利益，并用画面证明'], ['复制竞品视频', '只参考节奏、演示或顾虑处理，不复制措辞'], ['让它爆', '让产品、受众和证明不靠额外解释也能看懂']]), P('WEM 可以提供参考视频，但会标注每条参考到底学什么，例如开头 tension、镜头、证明顺序、顾虑回答或 CTA。')] },
      { id: 'claims', h: '把产品事实、功效 Claims 和个人体验分开', body: [P('品牌有责任给达人准确资料。美妆、健康、保健品、食品、母婴等高信任品类更需要边界。包装或批准资料支持的产品事实，不等于可以保证结果；达人个人体验也不能替代品牌需要证明的 claims。'), UL(['用自然语言提供已经批准的产品事实', '对医疗、比较、环保或保证结果等 claims 设置审核', '明确哪些词或暗示不能使用', '不能鼓励达人编造稀缺、背书或个人结果', '把短期 offer 和长期产品事实分开', '不确定的 claims 交给品牌合资格负责人']), P('WEM 可以协调流程、帮助达人理解 brief，但不能替代品牌的法务和合规顾问。')] },
      { id: '交付和权利', h: '交付、审核和使用权必须写清楚', body: [P('Affiliate 佣金、免费样品、固定达人费用和付费广告使用权是不同的事情。Brief 必须和实际协议、平台合作方式一致，不能默认寄出产品就自动拥有视频。'), TABLE(['项目', '必须回答的问题'], [['交付形式', '挂车视频、直播、raw footage、剪辑 UGC 还是其他格式？'], ['审核', '品牌只有事实审核、完整发布前审批，还是没有预审？'], ['修改', '包含几轮修改，什么情况可以要求修改？'], ['自然使用', '品牌能否 repost、embed 或分享？'], ['付费使用', '是否包括 Spark Ads、whitelisting、GMV Max、Meta、Amazon 或官网？'], ['时间与地区', '可以使用多久、在哪些地区使用？'], ['排他', '是否有品类或竞品限制？']]), P('TikTok Shop 已提供带内容审核与节点追踪的 flat-fee collaboration 流程。具体功能和条款应以 Seller Center 与适用协议为准。')] },
      { id: '审核', h: '用决策清单审核内容', body: [P('审核应该保护事实、改善清晰度，而不是把所有达人改成同一种说话方式。WEM 会把必须修改和可选创意建议分开。'), UL(['产品和规格是否正确？', '商品链接是否正确？', 'Claims 是否准确并在边界内？', '观众能否很快理解问题和产品作用？', '证明是否在画面中可见？', '是否按要求披露合作关系？', 'Offer、价格、库存与物流表达是否仍然有效？', '内容是否保留达人自然语气？', '进入广告或跨渠道使用前，是否已有权利文件？']), P('内容发布后，评论、问题、观看、点击、订单和退货还要继续反馈到下一版 brief。')] },
      { id: 'wem怎么做', h: 'WEM 怎么建立和迭代达人 Brief？', body: [P('WEM 会把 brief 和达人筛选、商品页、寄样状态、内容表现连在一起，不会给所有达人发送同一份通用模板。WEM 的 content coach 可以做内容审核、具体反馈，并为达人或品牌团队提供 training call。'), UL(['和品牌确认产品事实与受众问题', '按达人格式和受众设计内容任务', '需要扩大覆盖时，从活跃的 8,000+ affiliate / creator 社群中继续招募', '支持 cold start 和新品起盘阶段更快激活达人，同时保留匹配审核', '提供 content review、达人反馈和 training call', '把必须修改与主观创意偏好分开', '把达人和用户问题反馈给商品页与下一轮 brief', '识别值得复合作、谈使用权或进入付费评估的内容']), P('当品牌的 brief 不一致、达人反复问同样问题、claims 经常跑偏、内容没有视觉证明，或者多个团队无法维护同一份产品信息时，就适合找 WEM。'), CTA('查看 WEM 的项目与能力 →', '/showcase.html'), CTA('和 WEM 讨论达人内容系统 →')] },
    ],
    faqs: [
      { q: 'TikTok Shop 达人 Brief 怎么写？', a: '先写受众问题和产品事实，再补充可视化证明、重点卖点、claims 边界、正确商品与 offer、交付、时间、审核、使用权和联系人。要说明内容任务，但不要把达人表达写死。' },
      { q: '达人 Brief 要不要写完整脚本？', a: '通常不需要。完整脚本容易降低真实感。只有必要披露、法律文字或必须精确表达的批准 claims，才适合要求固定措辞。' },
      { q: '免费寄样以后，品牌可以直接使用达人视频吗？', a: '不一定。免费产品、affiliate 佣金、达人费用、自然 repost 和付费广告使用权是不同的，应根据适用协议确认。' },
      { q: 'TikTok Shop 视频发布前应该审核什么？', a: '重点检查产品和链接、claims、披露、必讲事实、offer 准确性、可视化证明和约定交付，并把必须修改与主观偏好分开。' },
      { q: 'WEM 可以帮品牌写和管理达人 Brief 吗？', a: '可以。WEM 会按达人和产品建立 brief、协调寄样与问题、审核事实和交付、收集达人与用户反馈，并把学习用于下一轮内容和商品页。' },
    ],
    related: [{ label: '品牌怎么找 TikTok Shop 达人', href: 'how-to-find-creators-for-your-brand-tiktok-shop.html' }, { label: 'TikTok Shop 达人联盟管理', href: 'tiktok-shop-creator-affiliate-management.html' }, { label: 'TikTok Shop 寄样 ROI', href: 'tiktok-shop-sample-roi-tracking.html' }],
  }
};

function App() { const [lang, setLang] = useState(() => { const x = new URLSearchParams(window.location.search).get('lang'); if (x === 'zh' || x === 'en') return x; return localStorage.getItem('we-lang') || 'en'; }); const post = POSTS[lang]; useEffect(() => { localStorage.setItem('we-lang', lang); document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en'; document.title = `${post.meta.title} | WE Marketing`; }, [lang, post]); useEffect(() => { if (window.lucide) window.lucide.createIcons(); }); return <div data-screen-label="WE Blog · Creator Brief"><CursorStars /><NavBar lang={lang} onLang={setLang} basePath="../" /><BlogPost {...post} labels={LABELS[lang]} /><CtaFooter lang={lang} /><Footer lang={lang} basePath="../" /></div>; }
ReactDOM.createRoot(document.getElementById('root')).render(<App />);
